add rules

diff --git a/.github/workflows/azure-static-web-apps-zealous-pond-0313ec103.yml b/.github/workflows/azure-static-web-apps-zealous-pond-0313ec103.yml
--- a/.github/workflows/azure-static-web-apps-zealous-pond-0313ec103.yml
+++ b/.github/workflows/azure-static-web-apps-zealous-pond-0313ec103.yml
@@ -15,6 +15,13 @@ jobs:
     runs-on: ubuntu-latest
     name: Build and Deploy Job
     steps:
+      - name: Check PR Base Branch
+        if: github.event_name == 'pull_request'
+        run: |
+          if [[ "${{ github.base_ref }}" != 'main' ]] || [[ "${{ github.head_ref }}" != 'development' ]]; then
+            echo "::error::Pull request must be from 'development' to 'main'."
+            exit 1
+          fi
       - uses: actions/checkout@v3
         with:
           submodules: true
@@ -25,16 +32,15 @@ jobs:
       - name: Setup Node.js environment
         uses: actions/setup-node@v3
         with:
-          node-version: '18'  # Specify Node.js version, adjust as needed
+          node-version: '18'
       - name: Install Dependencies
         run: |
-          cd frontend  # Change directory to frontend where package.json is located
+          cd frontend
           npm install
       - name: Build Project
         run: |
-          cd frontend  # Ensure we are in the correct directory to build the project
+          cd frontend
           npm run build
-
       - name: Build And Deploy
         id: builddeploy
         uses: Azure/static-web-apps-deploy@v1
@@ -42,9 +48,9 @@ jobs:
           azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_POND_0313EC103 }}
           repo_token: ${{ secrets.GITHUB_TOKEN }}
           action: "upload"
-          app_location: "frontend" # App source code path
-          api_location: "backend" # Api source code path - optional!!!
-          output_location: "build" # Built app content directory - optional
+          app_location: "frontend"
+          api_location: "backend"
+          output_location: "build"
 
   close_pull_request_job:
     if: github.event_name == 'pull_request' && github.event.action == 'closed'
